id: IBEB4ECC7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:16:18+00:00'
last_modified: '2022-06-08T12:30:56.125773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25785
  title: ཨེ་ཝན་ཌེ་ནེ་སོ་ཝེ་ཆིས་ཀྱི་མི་ཚེ་ལས་ཉིན་གཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    B254:
      image_group_id: I1KG25787
      title: ''
      total_pages: 391
      order: 1
      base_file: B254.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
